services:

  db:
    image: postgres:16
    container_name: postgres_db

    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .

    container_name: fastapi_app

    ports:
      - "8000:8000"

    depends_on:
      - db

    volumes:
      - .:/app

volumes:
  postgres_data: